AllCops:
  Exclude:
    - 'spec/**'

Metrics/LineLength:
  # Change the default 80 chars limit value
  Max: 130
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false
